# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0002_auto_20170616_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('notes', models.TextField()),
                ('laps', models.PositiveSmallIntegerField(default=1)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.Routine')),
            ],
        ),
        migrations.CreateModel(
            name='SegmentExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.PositiveSmallIntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.Exercise')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.Segment')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='segment',
            name='workout_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.WorkoutType'),
        ),
    ]
